// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEGZAYZNPObxTWPgqp4kUFaWtgL4GnpCk',
    appId: '1:321137441087:web:867cf082f7abb9b1043b8a',
    messagingSenderId: '321137441087',
    projectId: 'balang-3',
    authDomain: 'balang-3.firebaseapp.com',
    storageBucket: 'balang-3.firebasestorage.app',
    measurementId: 'G-N4E7BVCPEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAg9x0aYeXNXG6QmhP9L9T0O6JOCRMeZk',
    appId: '1:321137441087:android:9e6e1c40eefda928043b8a',
    messagingSenderId: '321137441087',
    projectId: 'balang-3',
    storageBucket: 'balang-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOgF5J1dUWEKhL1K9fQlpbBxIbdbFgl4Q',
    appId: '1:321137441087:ios:76776ba1c4f494e4043b8a',
    messagingSenderId: '321137441087',
    projectId: 'balang-3',
    storageBucket: 'balang-3.firebasestorage.app',
    iosBundleId: 'com.example.flutterBalangApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOgF5J1dUWEKhL1K9fQlpbBxIbdbFgl4Q',
    appId: '1:321137441087:ios:76776ba1c4f494e4043b8a',
    messagingSenderId: '321137441087',
    projectId: 'balang-3',
    storageBucket: 'balang-3.firebasestorage.app',
    iosBundleId: 'com.example.flutterBalangApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEGZAYZNPObxTWPgqp4kUFaWtgL4GnpCk',
    appId: '1:321137441087:web:867cf082f7abb9b1043b8a',
    messagingSenderId: '321137441087',
    projectId: 'balang-3',
    authDomain: 'balang-3.firebaseapp.com',
    storageBucket: 'balang-3.firebasestorage.app',
    measurementId: 'G-N4E7BVCPEJ',
  );

}